version: '3.7'

services:
  etcd:
    container_name: etcd
    image: $REGISTRY:$ETCD_VERSION
    restart: unless-stopped
    entrypoint: /usr/local/bin/etcd
    command:
      - --name=$THIS_NAME
      - --data-dir=/var/lib/etcd
      - --initial-advertise-peer-urls=http://$THIS_IP:2380
      - --listen-peer-urls=http://0.0.0.0:2380
      - --listen-client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://$THIS_IP:2379
      - --initial-cluster-token=$TOKEN
      - --initial-cluster=$NAME_1=http://$HOST_1:2380,$NAME_2=http://$HOST_2:2380,$NAME_3=http://$HOST_3:2380
      - --initial-cluster-state=$CLUSTER_STATE
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - /data/etcd:/var/lib/etcd
